name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build HTML
      run: |
          chmod +x .github/workflow/build.sh
          .github/workflow/build.sh
      shell: bash

